<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>MetroFramework.Samples</RootNamespace>
    <AssemblyName>MetroFramework.Samples</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MetroFramework\MetroFramework.csproj" />
  </ItemGroup>
</Project>
