<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsTestProject>false</IsTestProject>
    <IsPackable>true</IsPackable>
    <RootNamespace>MetroFramework</RootNamespace>
    <AssemblyName>MetroFramework</AssemblyName>
    <Authors>Peter Rekdal Sunde / Sven Walters</Authors>
    <Version>3.0.0</Version>
    <UseWindowsForms>true</UseWindowsForms>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageId>ModernUI</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/elbruno/del-winforms-modernui</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryBranch>main</RepositoryBranch>
    <Description>
      Brings the new Modern UI alias Metro UI of Windows 8 to .NET Windows Forms applications.

      Supported platforms:

      Windows 10/11 (.NET 10)
    </Description>
  </PropertyGroup>
</Project>