<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsTestProject>false</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>MetroFramework.Demo</RootNamespace>
    <AssemblyName>MetroFramework.Demo</AssemblyName>
    <Authors>Peter Rekdal Sunde / Sven Walters</Authors>
    <Version>3.0.0</Version>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MetroFramework\MetroFramework.csproj" />
  </ItemGroup>
</Project>